### ISSUE TITLE
Application Error

### ISSUE THREAD

**Issue by FayasNoushad** [cyberboysumanjay/APIs#9] opened 2021-09-10 08:42 UTC
If you are the application administrator, you can access the [diagnostic resources](https://sumanjay.scm.azurewebsites.net/detectors).

**Comment by FayasNoushad** [comment] 2021-09-10 08:42
Please fix

**Comment by irlamplex** [comment] 2021-09-10 09:55
> Please fix

I am getting the error below:

:( Application Error
If you are the application administrator, you can access the diagnostic resources.

**Comment by irlamplex** [comment] 2021-09-10 09:55
I am getting the error below:

:( Application Error
If you are the application administrator, you can access the diagnostic resources.

**Comment by FayasNoushad** [comment] 2021-09-10 10:03
> I am getting the error below:
> 
> :( Application Error
> If you are the application administrator, you can access the diagnostic resources.

Same error for me.

**Comment by cyberboysumanjay** [comment] 2021-09-10 14:02
It seems Azure isn't happy with the API too 😞 
Anyways deployed API to Railway now 🥂 
Let me know if the issue is fixed now

**Comment by FayasNoushad** [comment] 2021-09-10 14:21
Ohh! Its working sir.

**Comment by cyberboysumanjay** [comment] 2021-09-10 14:29
Nice. 
Closing this issue now 👍🏻

**Closed by cyberboysumanjay** 2021-09-10 14:29 UTC
